### ISSUE TITLE
Build fails for iOS app

### ISSUE THREAD

**Issue by ndastur** [QuickBlox/quickblox-xamarin-sdk#3]
Build of the sample app fails for the iOS version with:

error CS0016: Could not write to file `XamarinFormsQbChatiOS'. The supplied byte array is not a valid .ico file.

Google around it might be related to a nordic characters bug, but in this project I can't find any nordic characters

**Comment by EduardoForever** [comment]
Hello, Could you clarify the problem. This reproduce at master or deb branch?

**Comment by ndastur** [comment]
Thank you @EduardoForever . It is on the master branch that the build fails.
I am building on OSX 10.10.5 using Xamarin Studio. And the about box details are below:

Google leads to https://forums.xamarin.com/discussion/68505/update-tamarin-causes-error

```
Xamarin Studio Community
Version 6.0.1 (build 9)
Installation UUID: 4a8bfe62-6cf2-4941-9e63-219d1168c1be
Runtime:
    Mono 4.4.1 (mono-4.4.0-branch-c7sr0/4747417) (64-bit)
    GTK+ 2.24.23 (Raleigh theme)

    Package version: 404010000

Xamarin.Profiler
Not Installed

Apple Developer Tools
Xcode 7.2 (9548)
Build 7C68

Xamarin.Mac
Version: 2.8.1.4 (Xamarin Studio Community)

Xamarin.Android
Version: 6.1.1.1 (Xamarin Studio Community)
Android SDK: /Users/nevilledastur/Library/Developer/Xamarin/android-sdk-macosx
    Supported Android versions:
        6.0 (API level 23)

SDK Tools Version: 25.1.2
SDK Platform Tools Version: 24.0.0
SDK Build Tools Version: 23.0.2

Java SDK: /usr
java version "1.7.0_80"
Java(TM) SE Runtime Environment (build 1.7.0_80-b15)
Java HotSpot(TM) 64-Bit Server VM (build 24.80-b11, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL
```

**Comment by EduardoForever** [comment]
I've updated master brunch, you can check

**Comment by ndastur** [comment]
Thank you. Master now builds fine.
Can I ask what the specific bug was as there have been a number of commits from dev branch and I couldn't tell. Thanks
